baseURL: "https://beaubressler.github.io"
title: "Beau Bressler"
theme: "PaperMod"

env: production
enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: research/
    - name: Teaching
      url: teaching/
    - name: CV
      url: cv.pdf

params:
  description: "Beau Bressler - PhD candidate in Economics at UC Davis specializing in urban economics, labor economics, and economic history."
  author: "Beau Bressler"
  images:
    - picture.jpeg
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  footer:
    custom: 'Inspired by <a href="https://pascalmichaillat.org" target="_blank">Pascal Michaillat</a>' 
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: "Beau Bressler"
    subtitle: "Hello! I am a Ph.D. candidate in the <a href=\"https://economics.ucdavis.edu/\" target=\"_blank\">Department of Economics</a> at the University of California, Davis. I am an applied microeconomist working at the intersection of <strong>urban economics, economic history, labor</strong> and <strong>public economics</strong>.<br><br><strong>I am on the 2025/2026 job market.</strong><br><br>My job market paper studies the long-run effects of the American public housing program on neighborhoods."
    imageUrl: "picture.jpeg"
    imageWidth: 350
    imageHeight: 389
    buttons:
      - name: Research
        url: research/
      - name: Teaching
        url: teaching/
      - name: CV
        url: cv.pdf

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:blbressler@ucdavis.edu
    - name: GitHub
      url: https://github.com/beaubressler

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Beau Bressler"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2