baseURL: "https://beaubressler.github.io"
title: "Beau Bressler"
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: research/
    - name: Teaching
      url: teaching/
    - name: CV
      url: cv.pdf

params:
  description: "Beau Bressler - PhD candidate in Economics at UC Davis specializing in urban economics, labor economics, and economic history."
  author: "Beau Bressler"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  footer:
    custom: 'Inspired by <a href="https://pascalmichaillat.org" target="_blank">Pascal Michaillat</a>' 
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: "Beau Bressler"
    subtitle: "Hello! I am a PhD candidate in Economics at UC Davis. My main research interests are in urban economics, labor economics, and economic history."
    imageUrl: "picture.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Research
        url: research/
      - name: Teaching
        url: teaching/
      - name: CV
        url: cv.pdf

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:blbressler@ucdavis.edu
    - name: GitHub
      url: https://github.com/beaubressler

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Beau Bressler"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2