baseURL: "https://beaubressler.github.io"
title: "Beau Bressler"
theme: "PaperMod"

env: production
googleAnalytics: G-4T9LT79JN5
enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: research/
    - name: Teaching
      url: teaching/
    - name: CV
      url: cv.pdf

params:
  googleAnalyticsID: G-4T9LT79JN5
  description: "Beau Bressler - PhD candidate in Economics at UC Davis specializing in urban economics, economic history, and public economics"
  author: "Beau Bressler"
  images:
    - /picture.jpg
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  footer:
    custom: 'Inspired by <a href="https://pascalmichaillat.org" target="_blank">Pascal Michaillat</a>' 
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: "Beau Bressler"
    subtitle:
     "Hello! I am a Ph.D. candidate in the <a href=\"https://economics.ucdavis.edu/\" target=\"_blank\">Department of Economics</a> at the University of California, Davis.
    I am an applied microeconomist working at the intersection of <strong>urban economics, economic history, public</strong> and <strong>labor economics</strong>.<br><br><strong>I am on the 2025/2026 job market.</strong><br>
    <br>My research studies how 20th-century urban policies shaped segregation, housing affordability, and neighborhood opportunity in American cities.
    
     My job market paper studies the long-run effects of the American mid-century public housing program on neighborhoods using a newly constructed national dataset.<br>
    <br>My second chapter, joint with <a href="https://www.tom-cui.com/" target="_blank">Tianfang Cui</a>, examines how the 1960s Urban Planning Assistance Program reduced housing supply and institutionalized exclusionary zoning practices.

     <br>You can contact me at <strong><a href=\"mailto:blbressler@ucdavis.edu\">blbressler@ucdavis.edu</a></strong>."
    imageUrl: "picture.jpg"
    imageWidth: 350
    imageHeight: 467
    buttons:
      - name: Research
        url: research/
      - name: Teaching
        url: teaching/
      - name: CV
        url: cv.pdf

  socialIcons: []

  assets:
    disableScrollBarStyle: true
    apple_touch_icon: apple-touch-icon.jpg

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Beau Bressler"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2